------------------------------------------------------
--Queries to pull data from school db.
------------------------------------------------------

--1). Provide all active PRE-K (3 AND 4 years) students and their primary contact data. 
--    **** Notice students with MISSING contact data. ****


SELECT STUDENT.STUDENT_ID, 
       STUDENT.FIRST_NAME, 
       STUDENT.LAST_NAME, 
       TYP.TYPE_NAME, 
       CONTACT.FIRST_NAME, 
       CONTACT.LAST_NAME, 
       CONTACT.PRIMARY_PHONE, 
       CONTACT.EMAIL
 FROM SCHOOL.STUDENT STUDENT
 LEFT  JOIN SCHOOL.CONTACTS CONTACT ON STUDENT.STUDENT_ID = CONTACT.STUDENT_ID AND CONTACT.IS_PRIMARY IS TRUE
 LEFT  JOIN SCHOOL.TYPE TYP ON TYP.TYPE_ID = CONTACT.RELATION_TYP
 WHERE STUDENT.STATUS_TYP = 2 
  AND STUDENT.STUDENT_ID IN 
  (
    SELECT STUDENTASC.STUDENT_ID FROM SCHOOL.CLASSROOM CLASS INNER JOIN SCHOOL.CLASSROOM_STUDENT STUDENTASC ON CLASS.CLASSROOM_ID = STUDENTASC.CLASSROOM_ID 
    WHERE CLASS.GRADE_TYP IN (21,22) AND STUDENTASC.END_DATE IS NULL
  )

;
--2). Provide all active students of "PRE-KG 3 YRS" grade ALONG with their class room, TEACHER details.

SELECT STUDENT.STUDENT_ID, 
       STUDENT.FIRST_NAME, 
       STUDENT.LAST_NAME,
       STUDENT.JOIN_DATE,
       CLASSROOM.YEAR CLASSROOM_YEAR,
       CLASSROOM.SECTION,
       CLASSROOM.STAFF_ID,
       STAFF.TITLE,
       STAFF.FIRST_NAME,
       STAFF.LAST_NAME
 FROM SCHOOL.STUDENT STUDENT
  INNER JOIN SCHOOL.CLASSROOM_STUDENT CLS_STU_ASC ON CLS_STU_ASC.STUDENT_ID = STUDENT.STUDENT_ID AND CLS_STU_ASC.END_DATE IS NULL
  INNER JOIN SCHOOL.CLASSROOM CLASSROOM ON CLS_STU_ASC.CLASSROOM_ID = CLASSROOM.CLASSROOM_ID
  INNER JOIN SCHOOL.STAFF STAFF ON STAFF.STAFF_ID = CLASSROOM.STAFF_ID
 WHERE STUDENT.STATUS_TYP = 2 AND CLASSROOM.GRADE_TYP = 21 -- 21 is "PRE-KG 3 YRS" , from type table
 ORDER BY STUDENT.JOIN_DATE
  
;
--3). Provide attendance report of tardy or absent students as on 08/15/2014 - Include basic details like student ids, names, class room, teacher, primary contact phone.

SELECT 
       ATT.ATTENDANCE_DATE,
       STUDENT.STUDENT_ID, 
       STUDENT.FIRST_NAME, 
       STUDENT.LAST_NAME,
       (SELECT TYPE_NAME FROM SCHOOL.TYPE WHERE ATT.ATTENDANCE_STATUS_TYP = TYPE_ID) AS ABSENT_TARDY,
       CLASSROOM.YEAR CLASSROOM_YEAR,
       CLASSROOM.SECTION AS CLASS_SECTION,
       STAFF.FIRST_NAME ||' '||STAFF.LAST_NAME AS TEACHER_NAME,
       CONTACT.PRIMARY_PHONE AS PARENT_PHONE, 
       CONTACT.EMAIL AS PARENT_EMAIL
 FROM SCHOOL.STUDENT STUDENT
  INNER JOIN SCHOOL.CLASSROOM_STUDENT CLS_STU_ASC ON CLS_STU_ASC.STUDENT_ID = STUDENT.STUDENT_ID AND CLS_STU_ASC.END_DATE IS NULL
  INNER JOIN SCHOOL.CLASSROOM CLASSROOM ON CLS_STU_ASC.CLASSROOM_ID = CLASSROOM.CLASSROOM_ID
  INNER JOIN SCHOOL.STAFF STAFF ON STAFF.STAFF_ID = CLASSROOM.STAFF_ID
  INNER JOIN SCHOOL.ATTENDANCE ATT ON ATT.STUDENT_ID = STUDENT.STUDENT_ID AND ATT.ATTENDANCE_STATUS_TYP IN (37,38) -- 37 is TARDY, 38 is ABSENT
  LEFT  JOIN SCHOOL.CONTACTS CONTACT ON STUDENT.STUDENT_ID = CONTACT.STUDENT_ID AND CONTACT.IS_PRIMARY IS TRUE
 WHERE STUDENT.STATUS_TYP = 2 






